name: Greeting on variable day

on:
  workflow_dispatch
  
  env:
    DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
     Greeting: Hello 
    steps:
     - name: "Say Hello Daryan Its Monday"
       run: echo "$Greeting $fisrt_Name. Today is $DAY_OF_WEEK!"
       env: 
        First_Name: Daryan
 
