name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest  # Corrección en el nombre del runner
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Dar, it's Monday"
        run: echo "${{ env.Greeting }} ${{ env.First_Name }}. Today is ${{ env.DAY_OF_WEEK }}!"
        env:
          First_Name: Dar
